# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_settings.ui'
#
# Created: Thu Mar  8 13:47:35 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName(_fromUtf8("Settings"))
        Settings.resize(393, 423)
        Settings.setWindowTitle(QtGui.QApplication.translate("Settings", "IntersectIt :: settings", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout = QtGui.QGridLayout(Settings)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_2 = QtGui.QGroupBox(Settings)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Settings", "Observations", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.snapBox = QtGui.QCheckBox(self.groupBox_2)
        self.snapBox.setText(QtGui.QApplication.translate("Settings", "Snap to layers to place distances", None, QtGui.QApplication.UnicodeUTF8))
        self.snapBox.setChecked(True)
        self.snapBox.setObjectName(_fromUtf8("snapBox"))
        self.gridLayout_4.addWidget(self.snapBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 4)
        self.line = QtGui.QFrame(Settings)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 6, 0, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 13, 0, 1, 4)
        self.groupBox_3 = QtGui.QGroupBox(Settings)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Settings", "Intersection", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setText(QtGui.QApplication.translate("Settings", "Tolerance", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pixels = QtGui.QRadioButton(self.groupBox)
        self.pixels.setText(QtGui.QApplication.translate("Settings", "pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.pixels.setObjectName(_fromUtf8("pixels"))
        self.gridLayout_2.addWidget(self.pixels, 2, 0, 1, 1)
        self.mapUnits = QtGui.QRadioButton(self.groupBox)
        self.mapUnits.setText(QtGui.QApplication.translate("Settings", "map units", None, QtGui.QApplication.UnicodeUTF8))
        self.mapUnits.setChecked(True)
        self.mapUnits.setObjectName(_fromUtf8("mapUnits"))
        self.gridLayout_2.addWidget(self.mapUnits, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 2, 1, 1)
        self.tolerance = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.tolerance.setSingleStep(0.1)
        self.tolerance.setProperty("value", 0.3)
        self.tolerance.setObjectName(_fromUtf8("tolerance"))
        self.gridLayout_3.addWidget(self.tolerance, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setText(QtGui.QApplication.translate("Settings", "Selected observations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.rubberWidth = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.rubberWidth.setToolTip(_fromUtf8(""))
        self.rubberWidth.setDecimals(1)
        self.rubberWidth.setSingleStep(1.0)
        self.rubberWidth.setProperty("value", 2.0)
        self.rubberWidth.setObjectName(_fromUtf8("rubberWidth"))
        self.gridLayout_3.addWidget(self.rubberWidth, 2, 1, 1, 1)
        self.rubberColor = QtGui.QPushButton(self.groupBox_3)
        self.rubberColor.setToolTip(_fromUtf8(""))
        self.rubberColor.setText(_fromUtf8(""))
        self.rubberColor.setObjectName(_fromUtf8("rubberColor"))
        self.gridLayout_3.addWidget(self.rubberColor, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 3, 0, 1, 4)
        self.line_2 = QtGui.QFrame(Settings)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 4)
        self.groupBox_4 = QtGui.QGroupBox(Settings)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Settings", "Dimensions", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.placeArcBox = QtGui.QCheckBox(self.groupBox_4)
        self.placeArcBox.setText(QtGui.QApplication.translate("Settings", "place dimension arc in layer", None, QtGui.QApplication.UnicodeUTF8))
        self.placeArcBox.setChecked(True)
        self.placeArcBox.setObjectName(_fromUtf8("placeArcBox"))
        self.gridLayout_5.addWidget(self.placeArcBox, 0, 0, 1, 1)
        self.layerCombo = QtGui.QComboBox(self.groupBox_4)
        self.layerCombo.setObjectName(_fromUtf8("layerCombo"))
        self.gridLayout_5.addWidget(self.layerCombo, 0, 1, 1, 1)
        self.placeDimensionBox = QtGui.QCheckBox(self.groupBox_4)
        self.placeDimensionBox.setText(QtGui.QApplication.translate("Settings", "place dimension in field", None, QtGui.QApplication.UnicodeUTF8))
        self.placeDimensionBox.setChecked(True)
        self.placeDimensionBox.setObjectName(_fromUtf8("placeDimensionBox"))
        self.gridLayout_5.addWidget(self.placeDimensionBox, 1, 0, 1, 1)
        self.dimensionFieldCombo = QtGui.QComboBox(self.groupBox_4)
        self.dimensionFieldCombo.setObjectName(_fromUtf8("dimensionFieldCombo"))
        self.gridLayout_5.addWidget(self.dimensionFieldCombo, 1, 1, 1, 1)
        self.placePrecisionBox = QtGui.QCheckBox(self.groupBox_4)
        self.placePrecisionBox.setText(QtGui.QApplication.translate("Settings", "place precision in field", None, QtGui.QApplication.UnicodeUTF8))
        self.placePrecisionBox.setObjectName(_fromUtf8("placePrecisionBox"))
        self.gridLayout_5.addWidget(self.placePrecisionBox, 2, 0, 1, 1)
        self.precisionFieldCombo = QtGui.QComboBox(self.groupBox_4)
        self.precisionFieldCombo.setObjectName(_fromUtf8("precisionFieldCombo"))
        self.gridLayout_5.addWidget(self.precisionFieldCombo, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 7, 0, 1, 4)

        self.retranslateUi(Settings)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Settings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)
        Settings.setTabOrder(self.pixels, self.buttonBox)

    def retranslateUi(self, Settings):
        pass

