# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_settings.ui'
#
# Created: Wed Mar 27 11:12:43 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName(_fromUtf8("Settings"))
        Settings.resize(427, 472)
        self.gridLayout = QtGui.QGridLayout(Settings)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(Settings)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.observationTab = QtGui.QWidget()
        self.observationTab.setObjectName(_fromUtf8("observationTab"))
        self.formLayout_2 = QtGui.QFormLayout(self.observationTab)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.obsSnapping = QtGui.QCheckBox(self.observationTab)
        self.obsSnapping.setChecked(True)
        self.obsSnapping.setObjectName(_fromUtf8("obsSnapping"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.obsSnapping)
        self.label_3 = QtGui.QLabel(self.observationTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.obsDefaultPrecisionDistance = QtGui.QDoubleSpinBox(self.observationTab)
        self.obsDefaultPrecisionDistance.setDecimals(1)
        self.obsDefaultPrecisionDistance.setMaximum(1000.0)
        self.obsDefaultPrecisionDistance.setProperty("value", 25.0)
        self.obsDefaultPrecisionDistance.setObjectName(_fromUtf8("obsDefaultPrecisionDistance"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.obsDefaultPrecisionDistance)
        self.label_4 = QtGui.QLabel(self.observationTab)
        self.label_4.setEnabled(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.obsDefaultPrecisionOrientation = QtGui.QDoubleSpinBox(self.observationTab)
        self.obsDefaultPrecisionOrientation.setEnabled(False)
        self.obsDefaultPrecisionOrientation.setMaximum(2.0)
        self.obsDefaultPrecisionOrientation.setSingleStep(0.1)
        self.obsDefaultPrecisionOrientation.setProperty("value", 0.5)
        self.obsDefaultPrecisionOrientation.setObjectName(_fromUtf8("obsDefaultPrecisionOrientation"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.obsDefaultPrecisionOrientation)
        self.tabWidget.addTab(self.observationTab, _fromUtf8(""))
        self.intersectionTab = QtGui.QWidget()
        self.intersectionTab.setObjectName(_fromUtf8("intersectionTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.intersectionTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.selectGroup = QtGui.QGroupBox(self.intersectionTab)
        self.selectGroup.setObjectName(_fromUtf8("selectGroup"))
        self.gridLayout_3 = QtGui.QGridLayout(self.selectGroup)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.intersectRubberWidth = QtGui.QDoubleSpinBox(self.selectGroup)
        self.intersectRubberWidth.setToolTip(_fromUtf8(""))
        self.intersectRubberWidth.setDecimals(1)
        self.intersectRubberWidth.setSingleStep(1.0)
        self.intersectRubberWidth.setProperty("value", 2.0)
        self.intersectRubberWidth.setObjectName(_fromUtf8("intersectRubberWidth"))
        self.gridLayout_3.addWidget(self.intersectRubberWidth, 2, 1, 1, 1)
        self.widget = QtGui.QWidget(self.selectGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pixels = QtGui.QRadioButton(self.widget)
        self.pixels.setObjectName(_fromUtf8("pixels"))
        self.intersecSelectUnits = QtGui.QButtonGroup(Settings)
        self.intersecSelectUnits.setObjectName(_fromUtf8("intersecSelectUnits"))
        self.intersecSelectUnits.addButton(self.pixels)
        self.gridLayout_2.addWidget(self.pixels, 2, 0, 1, 1)
        self.map = QtGui.QRadioButton(self.widget)
        self.map.setChecked(True)
        self.map.setObjectName(_fromUtf8("map"))
        self.intersecSelectUnits.addButton(self.map)
        self.gridLayout_2.addWidget(self.map, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.selectGroup)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.intersecSelectTolerance = QtGui.QDoubleSpinBox(self.selectGroup)
        self.intersecSelectTolerance.setSingleStep(0.1)
        self.intersecSelectTolerance.setProperty("value", 0.3)
        self.intersecSelectTolerance.setObjectName(_fromUtf8("intersecSelectTolerance"))
        self.gridLayout_3.addWidget(self.intersecSelectTolerance, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.selectGroup)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.intersectRubberColor = QtGui.QLabel(self.selectGroup)
        self.intersectRubberColor.setText(_fromUtf8(""))
        self.intersectRubberColor.setObjectName(_fromUtf8("intersectRubberColor"))
        self.gridLayout_3.addWidget(self.intersectRubberColor, 2, 2, 1, 1)
        self.gridLayout_4.addWidget(self.selectGroup, 0, 0, 1, 1)
        self.resultGroup = QtGui.QGroupBox(self.intersectionTab)
        self.resultGroup.setObjectName(_fromUtf8("resultGroup"))
        self.gridLayout_6 = QtGui.QGridLayout(self.resultGroup)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.intersecResultConfirm = QtGui.QCheckBox(self.resultGroup)
        self.intersecResultConfirm.setChecked(True)
        self.intersecResultConfirm.setObjectName(_fromUtf8("intersecResultConfirm"))
        self.gridLayout_6.addWidget(self.intersecResultConfirm, 0, 0, 1, 2)
        self.intersecResultPlaceReport = QtGui.QCheckBox(self.resultGroup)
        self.intersecResultPlaceReport.setObjectName(_fromUtf8("intersecResultPlaceReport"))
        self.gridLayout_6.addWidget(self.intersecResultPlaceReport, 2, 0, 1, 1)
        self.reportField = QtGui.QComboBox(self.resultGroup)
        self.reportField.setObjectName(_fromUtf8("reportField"))
        self.gridLayout_6.addWidget(self.reportField, 2, 1, 1, 1)
        self.intersecResultPlacePoint = QtGui.QCheckBox(self.resultGroup)
        self.intersecResultPlacePoint.setObjectName(_fromUtf8("intersecResultPlacePoint"))
        self.gridLayout_6.addWidget(self.intersecResultPlacePoint, 1, 0, 1, 1)
        self.intersectionLayer = QtGui.QComboBox(self.resultGroup)
        self.intersectionLayer.setObjectName(_fromUtf8("intersectionLayer"))
        self.gridLayout_6.addWidget(self.intersectionLayer, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.resultGroup, 4, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.intersectionTab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_4.addWidget(self.line_4, 3, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.intersectionTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.intersecLSconvergeThreshold = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.intersecLSconvergeThreshold.setDecimals(4)
        self.intersecLSconvergeThreshold.setMaximum(1.0)
        self.intersecLSconvergeThreshold.setSingleStep(0.01)
        self.intersecLSconvergeThreshold.setProperty("value", 0.0005)
        self.intersecLSconvergeThreshold.setObjectName(_fromUtf8("intersecLSconvergeThreshold"))
        self.gridLayout_5.addWidget(self.intersecLSconvergeThreshold, 0, 1, 1, 1)
        self.intersecLSmaxIter = QtGui.QSpinBox(self.groupBox_2)
        self.intersecLSmaxIter.setProperty("value", 15)
        self.intersecLSmaxIter.setObjectName(_fromUtf8("intersecLSmaxIter"))
        self.gridLayout_5.addWidget(self.intersecLSmaxIter, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.line = QtGui.QFrame(self.intersectionTab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 1)
        self.tabWidget.addTab(self.intersectionTab, _fromUtf8(""))
        self.dimensionTab = QtGui.QWidget()
        self.dimensionTab.setObjectName(_fromUtf8("dimensionTab"))
        self.formLayout = QtGui.QFormLayout(self.dimensionTab)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.dimenPlaceDimension = QtGui.QCheckBox(self.dimensionTab)
        self.dimenPlaceDimension.setChecked(True)
        self.dimenPlaceDimension.setObjectName(_fromUtf8("dimenPlaceDimension"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.dimenPlaceDimension)
        self.dimensionLayer = QtGui.QComboBox(self.dimensionTab)
        self.dimensionLayer.setObjectName(_fromUtf8("dimensionLayer"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.dimensionLayer)
        self.dimenPlaceMeasure = QtGui.QCheckBox(self.dimensionTab)
        self.dimenPlaceMeasure.setChecked(True)
        self.dimenPlaceMeasure.setObjectName(_fromUtf8("dimenPlaceMeasure"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.dimenPlaceMeasure)
        self.measureField = QtGui.QComboBox(self.dimensionTab)
        self.measureField.setObjectName(_fromUtf8("measureField"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.measureField)
        self.dimenPlacePrecision = QtGui.QCheckBox(self.dimensionTab)
        self.dimenPlacePrecision.setObjectName(_fromUtf8("dimenPlacePrecision"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.dimenPlacePrecision)
        self.precisionField = QtGui.QComboBox(self.dimensionTab)
        self.precisionField.setObjectName(_fromUtf8("precisionField"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.precisionField)
        self.tabWidget.addTab(self.dimensionTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Settings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)
        Settings.setTabOrder(self.pixels, self.buttonBox)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QtGui.QApplication.translate("Settings", "IntersectIt :: settings", None, QtGui.QApplication.UnicodeUTF8))
        self.obsSnapping.setText(QtGui.QApplication.translate("Settings", "Snap to layers to place observations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Settings", "Default precision for distances [1/1000 units]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Settings", "Default precision for orientations [°]", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.observationTab), QtGui.QApplication.translate("Settings", "Observations", None, QtGui.QApplication.UnicodeUTF8))
        self.selectGroup.setTitle(QtGui.QApplication.translate("Settings", "Selection of observations", None, QtGui.QApplication.UnicodeUTF8))
        self.pixels.setText(QtGui.QApplication.translate("Settings", "pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.map.setText(QtGui.QApplication.translate("Settings", "map units", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Settings", "highlighting", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Settings", "select observations within", None, QtGui.QApplication.UnicodeUTF8))
        self.resultGroup.setTitle(QtGui.QApplication.translate("Settings", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.intersecResultConfirm.setText(QtGui.QApplication.translate("Settings", "ask to validate intersection results", None, QtGui.QApplication.UnicodeUTF8))
        self.intersecResultPlaceReport.setText(QtGui.QApplication.translate("Settings", "place LS report in field", None, QtGui.QApplication.UnicodeUTF8))
        self.intersecResultPlacePoint.setText(QtGui.QApplication.translate("Settings", "place point in layer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Settings", "Least-squares", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Settings", "Convergence threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Settings", "map units", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Settings", "Maximum iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.intersectionTab), QtGui.QApplication.translate("Settings", "Intersection", None, QtGui.QApplication.UnicodeUTF8))
        self.dimenPlaceDimension.setText(QtGui.QApplication.translate("Settings", "place dimension arc in layer", None, QtGui.QApplication.UnicodeUTF8))
        self.dimenPlaceMeasure.setText(QtGui.QApplication.translate("Settings", "place measure in field", None, QtGui.QApplication.UnicodeUTF8))
        self.dimenPlacePrecision.setText(QtGui.QApplication.translate("Settings", "place precision in field", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dimensionTab), QtGui.QApplication.translate("Settings", "Dimensions", None, QtGui.QApplication.UnicodeUTF8))

